version: 0.16.{build}

branches:
  only:
    - appveyor
    - develop
    - /release\/.*/

skip_tags: true
max_jobs: 1
image: Ubuntu1604
stack: node 10, jdk 8

build_script:
- sudo -E bash -s <<EOF
  python2 -m pip install awscli==1.14.56 mkdocs
  bash deploy/appveyor/appveyor_pack_dist.sh
  EOF

test: off
