version: 0.16.{build}

branches:
  only:
    - appveyor
    - develop
    - /release\/.*/

skip_tags: true
max_jobs: 1
image: Ubuntu1604
stack: node 10, jdk 8
init:
  - python2 -m pip install awscli==1.14.56 mkdocs

build_script:
- whoami ;
  sudo su - ;
  whoami

test: off
