apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-search-srv: "true"
  name: cp-search-srv
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${CP_SEARCH_INTERNAL_PORT}
    targetPort: 8080
    name: cp-search-srv-port
  selector:
    cloud-pipeline/cp-search-srv: "true"
