apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-billing-srv: "true"
  name: cp-billing-srv
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: ${CP_billing_INTERNAL_PORT}
      targetPort: 8080
      name: cp-billing-srv-port
  selector:
    cloud-pipeline/cp-billing-srv: "true"
