apiVersion: v1
kind: Service
metadata:
  labels:
    cloud-pipeline/cp-api-db: "true"
  name: cp-api-db
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: ${PSG_PORT}
    targetPort: ${PSG_PORT}
  selector:
    cloud-pipeline/cp-api-db: "true"
